spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${CLIENT_DB_HOST}:${CLIENT_DB_PORT}/${CLIENT_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${CLIENT_DB_USERNAME}
    password: ${CLIENT_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect